Update token variable for ops-and-sops access

diff --git a/.github/workflows/portmason-setup-and-deploy.yml b/.github/workflows/portmason-setup-and-deploy.yml
--- a/.github/workflows/portmason-setup-and-deploy.yml
+++ b/.github/workflows/portmason-setup-and-deploy.yml
@@ -30,7 +30,7 @@ jobs:
       DEPLOY_DIR: site/deploy/prd
       PAGES_SITE_DIR: site/deploy/prd/www
       OPS_DIR: ops-and-sops
-      OPS_AND_SOPS_READ_TOKEN_2: ${{ secrets.OPS_AND_SOPS_READ_TOKEN_2 }}
+      OPS_AND_SOPS_READ_TOKEN_3: ${{ secrets.OPS_AND_SOPS_READ_TOKEN_3 }}
 
     steps:
       - name: Check out project
@@ -44,13 +44,13 @@ jobs:
         run: |
           set -euo pipefail
 
-          [[ -n "${OPS_AND_SOPS_READ_TOKEN_2}" ]] || {
-            echo "::error::OPS_AND_SOPS_READ_TOKEN_2 is required to read private domer6811/ops-and-sops"
+          [[ -n "${OPS_AND_SOPS_READ_TOKEN_3}" ]] || {
+            echo "::error::OPS_AND_SOPS_READ_TOKEN_3 is required to read private domer6811/ops-and-sops"
             exit 1
           }
 
           mkdir $OPS_DIR
-          export GITHUB_TOKEN="${OPS_AND_SOPS_READ_TOKEN_2}"
+          export GITHUB_TOKEN="${OPS_AND_SOPS_READ_TOKEN_3}"
 
           git clone --filter=blob:none --sparse https://x-access-token:${GITHUB_TOKEN}@github.com/domer6811/ops-and-sops.git $OPS_DIR
           cd $OPS_DIR
